blueprint: service_template
title: Terraform Template
identifier: terraform_template
properties:
  readme: file://README.md
  cookiecutter_properties: file://cookiecutter.json
relations:
  git_hub_repository_identifier: v1vhm/template-terraform-service
