version: 1
repository:
  topics: ["terraform","service","platform"]
  description: "Terraform-based service scaffold"
rulesets:
  - name: "trunk-based-for-terraform"
    target: "branch"
    enforcement: "active"
    conditions:
      ref_name:
        include: ["~DEFAULT_BRANCH"]
        exclude: []
    rules:
      - type: "deletion"
      - type: "non_fast_forward"
      - type: "pull_request"
        parameters:
          required_approving_review_count: 1
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: true
          require_last_push_approval: true
          required_review_thread_resolution: true
          allowed_merge_methods: ["merge","squash","rebase"]
      - type: "code_scanning"
        parameters:
          code_scanning_tools:
            - tool: "CodeQL"
      - type: "required_status_checks"
        parameters:
          strict_required_status_checks_policy: true
          do_not_enforce_on_create: true
          required_status_checks:
            - context: "tf-plan-summary"
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Bug or defect"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
teams:
  - team: "developers"
    permission: "push"
variables:
  - name: "ENVIRONMENT"
    value: "dev"
secrets:
  - name: "CLOUD_KV_URI"
    source: "workflow_secret"
    ref: "ORG_CLOUD_KV_URI"
