version: 1
repository:
  topics: ["terraform","service","platform"]
rulesets:
  - name: "trunk-based-for-terraform"
    target: "branch"
    enforcement: "active"
    conditions:
      ref_name:
        include: ["~DEFAULT_BRANCH"]
        exclude: []
    rules:
      - type: "deletion"
      - type: "non_fast_forward"
      - type: "pull_request"
        parameters:
          required_approving_review_count: 1
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: true
          require_last_push_approval: true
          required_review_thread_resolution: true
          allowed_merge_methods: ["merge","squash","rebase"]
      - type: "code_scanning"
        parameters:
          code_scanning_tools:
            - tool: "CodeQL"
      - type: "required_status_checks"
        parameters:
          strict_required_status_checks_policy: true
          do_not_enforce_on_create: true
          required_status_checks:
            - context: "tf-plan-summary"
  - name: "TF_PASSPHRASE"
    source: "workflow_secret"
    ref: "TMP_PASSPHRASE"
