name: cookiecutter

permissions:
  contents: read

on:
  push:
    paths:
      - 'cookiecutter.json'
      - '{{cookiecutter.repo_name}}/**'
  pull_request:
    paths:
      - 'cookiecutter.json'
      - '{{cookiecutter.repo_name}}/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter pyflakes
          TMP_LINT_DIR="$(mktemp -d)"
          echo "TMP_LINT_DIR=$TMP_LINT_DIR" >> $GITHUB_ENV
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest "$TMP_LINT_DIR"
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash -s -- -b "$TMP_LINT_DIR"
          sudo apt-get update && sudo apt-get install -y shellcheck
          echo "$TMP_LINT_DIR" >> $GITHUB_PATH
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Generate project
        run: cookiecutter --no-input --output-dir /tmp/test "$GITHUB_WORKSPACE"
      - name: Lint and validate
        run: |
          cd "$(ls -d /tmp/test/*)"
          actionlint .github/workflows/*.yml
          tflint --format=compact
          pyflakes .
          find . -name '*.sh' -exec shellcheck {} +
          terraform fmt -check
          terraform init -backend=false
          terraform validate
          rm -rf .terraform
