name: Terraform

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # TODO: Add steps for Terraform init/plan/apply using TF-via-PR action

name: Terraform

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create plugin cache
        run: |
          mkdir -p $HOME/.terraform.d/plugin-cache
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform plan or apply
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: .
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-lock: ${{ github.event_name == 'push' }}
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          validate: true
          format: true
